### ISSUE TITLE
Block content?

### ISSUE THREAD

**Issue by ksnyde** [huafu/ember-marked#6]
Am I right that this component can not work on block content? Seems like a great use-case:

    {{#code-section}}
        var foobar = 'hello world';
    {{/code-section}}

**Comment by huafu** [comment]
Yup, I never got the time to implement it, will try to find it one day but a PR will be more than welcome if you have time ;-)

--
Huafu Gandon

**Comment by ksnyde** [comment]
Will try to squeeze it in but sounds like we're both pinched for time. :)

**Comment by huafu** [comment]
Actually this is impossible since first you cannot grab the content of the `{{yield}}` from the component class, and also we need the raw text, and not some HTML or such, plus code sections contains a lot of `<` which would not work or you'd need to encode them and then the encoded version would appear in the code.

So nope, impossible => won't implement sorry ;-)

**Comment by ksnyde** [comment]
I thought it was in `content` property? WRT to raw text, can't you use `htmlSafe()`?

**Comment by huafu** [comment]
No it is not in content. HtmlSafe is to ensure an already in html string will not be escaped. And FYI after searching I asked a member of EmberJS core team about how to catch that... answer was "not possible".
If you can make it, do a PR ;-)
